server:
  port: 9006
spring:
  datasource:
    url: jdbc:h2:mem:springboot-jpa-h2 #数据库url配置
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_on_trans: true
    show-sql: true # 打印出sql语句
#    spring.jpa.hibernate.ddl-auto配置说明：
#    1. `create`:每次重新启动项目都会重新创新表结构，会导致数据丢失
#    2. `create-drop`:每次启动项目创建表结构，关闭项目删除表结构
#    3. `update`:每次启动项目会更新表结构
#    4. `validate`:验证表结构，不对数据库进行任何更改
    hibernate:
      ddl-auto: update
    open-in-view: false
  # h2 控制台
  h2:
    console:
      enabled: true
