server:
  port: 9001

baidu-url: https://www.baidu.com

my-account:
  name: Hrio
  email: 1085568138@qq.com

music:
  collect-name: 依然范特西
  songs:
    - name: 夜的第七章
      description: 《夜的第七章》是周杰伦、潘儿演唱的一首歌曲，由黄俊郎作词，周杰伦作曲，钟兴民、林迈可编曲，收录在周杰伦2006年9月5日发行的专辑《依然范特西》中
    - name: 本草纲目
      description: 《本草纲目》是周杰伦演唱的一首歌曲，由方文山作词，周杰伦作曲，林迈可编曲，收录在周杰伦2006年9月5日发行的专辑《依然范特西》中
    - name: 听妈妈的话
      description: 《听妈妈的话》是周杰伦演唱的一首歌曲，由周杰伦作词、作曲，林迈可、洪敬尧编曲，收录在周杰伦2006年9月5日发行的专辑《依然范特西》中
